api_platform:
    version: '0.0.1'
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/config/api_platform/resources']
    resource_class_directories:
        - '%kernel.project_dir%/src/CestManager/Collection/Entity'
        - '%kernel.project_dir%/src/CestManager/Scenario/Entity'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]