App\CestManager\Action\Entity\Action:
  description: 'A action which can be used inside Scenarios'
  
  id:
    generationStrategy: none

  properties:
    id:
      identifier: true
      generationStrategy: none
      writeable: true
      
  collectionOperations:
    get:
      method: 'GET'
  
  itemOperations:
    get:
      method: 'GET'