App\Entity\Collection:
  description: 'A collection of Scenarios'
  
  id:
    generationStrategy: none

  properties:
    scenario:
      subresource:
        resourceClass: 'App\Entity\Scenario'

  attributes:
    input: App\Dto\CollectionInput
    output: App\Dto\CollectionOutput
      
  collectionOperations:
    get:
      method: 'GET'
    post:
      method: 'POST'
  
  itemOperations:
    get:
      method: 'GET'
    put:
      method: 'PUT'
    delete:
      method: 'DELETE'