App\CestManager\Domain\Entity\Scenario:
  description: 'A collection of Scenarios'
#  attributes:
 #   normalization_context:
 #     groups: ['read']
 #   denormalization_context:
 #     groups: ['write']
#  id:
#    generationStrategy: none

  properties:
    id:
      identifier: true
      generationStrategy: none
      writeable: true


  collectionOperations:
    get:
      method: 'GET'
    post:
      method: 'POST'

  itemOperations:
    get:
      method: 'GET'
    put:
      method: 'PUT'
    delete:
      method: 'DELETE'
#    scenarios:
#      method: 'GET'
#      path: '/collections/{id}/scenarios'
      # Does not exist but needs to be supplied
#      controller: 'App/Controller/GetScenarios'
    #get_steps:
    #  method: 'GET'
    #  path: '/scenarios/{id}/steps'
      # Does not exist but needs to be supplied
    #  controller: 'App\Controller\GetSteps'

