App\Entity\Step:
  id:
    generationStrategy: none

  attributes:
    input: App\Dto\ScenarioInput
    output: App\Dto\ScenarioOutput
      
  collectionOperations: []
  
  itemOperations:
    get:
      method: 'GET'