<?php

declare(strict_types = 1);

namespace App\Tests\Fixtures\Cest;

/**
 * Codeception Cest generated by Fantestic.
 *
 * Feel free to add custom tests, any tests that do not have a 
 * @fantestic annotation will be ignored by Fantestic.
 * 
 * @author Fantestic
*/
class ListCest
{
    public function firstTest(\AcceptanceTester $I)
    {
        $I->amOnPage('/');
    }
}
